name: select_card_example_project
description: Select card example project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  select_card:
    path: ./path/select_card

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/clock.png
    - assets/cars/car1.png
    - assets/cars/car2.png
    - assets/cars/car3.png
    - assets/cars/car4.png
    - assets/cars/car5.png
    - assets/cars/car6.png
    - assets/cars/car7.png
    - assets/cakes/cake1.png
    - assets/cakes/cake2.png
    - assets/cakes/cake3.png
    - assets/cakes/cake4.png
    - assets/cakes/cake5.png
    - assets/cakes/cake6.png