name: select_card
description: A Flutter package with animated customizable card items selection.
version: 0.0.1
homepage: https://github.com/emrekaplanek
repository: https://github.com/emrekaplanek/select_card
documentation: https://github.com/emrekaplanek/select_card

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
